### ISSUE TITLE
Unable to install to VSTS

### ISSUE THREAD

**Issue by Afterlife88** [Microsoft/code-push-vsts-extension#26]
When I'm trying to install this extension to my VSTS account, I'm receiving this message

>   Extension operation denied by event callback. All the task versions belonging to Contribution Tasks/codepush-release should have the same task id. Tasks with version 1.0.5 and version 1.2.2 do not have same ids.

**Comment by alexandergoncharov** [comment]
Hi @Afterlife88 ,
Sorry for this really long delay!

Could you please clarify is issue still actual for you?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @Afterlife88,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
