### ISSUE TITLE
Can not specity the directory to execute the command code-push release-cordova

### ISSUE THREAD

**Issue by lvsezhufu** [Microsoft/code-push-vsts-extension#27]
This task is using the default working directory` $(Build.SourcesDirectory)`, and it can not be specified.

That means if the cordova app is not located in the root of the repo, the task will be failed with the message:

`Error: Current working directory is not a Cordova-based project`

It's very useful to add the option to specify the directory for this task, since the cordova app usually located in sub-folder instead of the root directory.

**Comment by alexandergoncharov** [comment]
Hi @lvsezhufu,
Sorry for this really long delay!

Could you please clarify is issue still actual for you?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @lvsezhufu ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
